import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  PAGE_PATHS_FILE,
  buildPagePaths,
  pageCount,
  renderModule,
  staticPagePaths,
} from '../scripts/generate-page-paths.mjs';
import { readCollection } from '../scripts/lib/content-frontmatter.mjs';
import { PAGE_PATHS } from '../src/data/page-paths.mjs';

/**
 * The generated page-path list, and the two places it can silently drift from the real routing.
 *
 * It is the bound on the `page` event class's key space (src/lib/agent-hits.mjs), so a list that
 * quietly stopped matching the site would not fail anything else: every path it lost would simply
 * bucket, and the page would report a run of `/*` rows nobody could explain.
 */

test('the committed file is what the generator would write', () => {
  // Regenerated by prebuild, so a stale one only survives a commit that skipped a build. Catching
  // it here means the diff is reviewable rather than arriving as a mystery on the deploy after.
  assert.equal(readFileSync(PAGE_PATHS_FILE, 'utf8'), renderModule(buildPagePaths()));
});

test('the generated module exports exactly what the generator built', () => {
  assert.deepEqual(PAGE_PATHS, buildPagePaths());
});

test('the section roots are derived from the page files, not transcribed', () => {
  const statics = staticPagePaths();
  for (const path of ['/', '/about', '/activity', '/projects', '/scorecard', '/steward', '/webmcp', '/writing']) {
    assert.ok(statics.includes(path), path);
  }
  // A dynamic route contributes nothing here: its paths come from the collections instead.
  assert.equal(statics.some((path) => path.includes('[')), false);
});

test('the changelog pager size matches the page that does the paginating', () => {
  // CHANGELOG_PAGE_SIZE is transcribed from src/pages/changelog/[...page].astro, which defines it
  // inside getStaticPaths because Astro runs that in an isolated scope. This is the join that
  // makes the copy safe: raise one without the other and the list loses its last ledger pages.
  const source = readFileSync(
    fileURLToPath(new URL('../src/pages/changelog/[...page].astro', import.meta.url)),
    'utf8'
  );
  const declared = source.match(/const PAGE_SIZE = (\d+);/);
  assert.ok(declared, 'the pager still declares PAGE_SIZE');

  const size = Number(declared[1]);
  assert.equal(pageCount(size), 1);
  assert.equal(pageCount(size + 1), 2);
  assert.equal(pageCount(0), 1, 'an empty changelog is still one page');
});

test('no draft slug is published in the list', () => {
  // This file is committed and rides into the middleware bundle, so a draft slug here would
  // publish the existence of an unpublished post. A draft also has no page to count: `draft: true`
  // keeps an entry out of getStaticPaths in every environment.
  //
  // Read from the collections rather than named, so the assertion holds whatever is in draft on the
  // day, including a draft that exists only in a working copy.
  for (const [collection, section] of [
    ['writing', '/writing'],
    ['changelog', '/changelog'],
  ]) {
    const entries = readCollection(fileURLToPath(new URL(`../src/content/${collection}/`, import.meta.url)));
    const published = entries.filter(({ data }) => data.draft !== true);
    assert.ok(entries.length > 0, collection);
    for (const { slug, data } of entries) {
      assert.equal(PAGE_PATHS.includes(`${section}/${slug}`), data.draft !== true, `${section}/${slug}`);
    }
    assert.ok(published.length > 0, `${collection} has at least one published entry`);
  }
});

test('the list is canonical, sorted and free of duplicates', () => {
  assert.deepEqual(PAGE_PATHS, [...PAGE_PATHS].sort());
  assert.equal(new Set(PAGE_PATHS).size, PAGE_PATHS.length);
  for (const path of PAGE_PATHS) {
    assert.ok(path.startsWith('/'), path);
    assert.equal(path === '/' || !path.endsWith('/'), true, path);
  }
});
